/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author User
 */
public class CadastroDeProfissionais extends javax.swing.JFrame {

    /**
     * Creates new form CadastroDeProfissionais
     */
    public CadastroDeProfissionais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoUsuario3 = new javax.swing.JTextField();
        CampoSenha = new javax.swing.JTextField();
        CampoEmail = new javax.swing.JTextField();
        CampoCertificado = new javax.swing.JTextField();
        CampoConfirmaSenha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VivaBem");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CampoUsuario3.setBorder(null);
        getContentPane().add(CampoUsuario3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, -1));

        CampoSenha.setBorder(null);
        getContentPane().add(CampoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, -1));

        CampoEmail.setBorder(null);
        getContentPane().add(CampoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 150, -1));

        CampoCertificado.setBorder(null);
        getContentPane().add(CampoCertificado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 140, -1));

        CampoConfirmaSenha.setBorder(null);
        getContentPane().add(CampoConfirmaSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 140, -1));

        jButton1.setText("CADASTRAR");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastro de Profissionais.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCertificado;
    private javax.swing.JTextField CampoConfirmaSenha;
    private javax.swing.JTextField CampoEmail;
    private javax.swing.JTextField CampoSenha;
    private javax.swing.JTextField CampoUsuario3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
